In [1]:
import pandas as pd
import numpy as np

# Creating a more complex dataframe with multi-index
index = pd.MultiIndex.from_tuples([('New York', 'Q1', 'one'), ('New York', 'Q1', 'two'),
                                   ('Los Angeles', 'Q1', 'one'), ('Los Angeles', 'Q1', 'two'),
                                   ('Chicago', 'Q2', 'one'), ('Chicago', 'Q2', 'two'),
                                   ('New York', 'Q2', 'one'), ('New York', 'Q2', 'two')],
                                  names=['City', 'Quarter', 'ID'])

# Creating random data for Sales, Profit, and Quantity
sales = np.round(np.random.uniform(100, 500, 8), 2)  # Sales between 100 and 500
profit = np.round(np.random.uniform(0, 0.35, 8), 2)     # Profit between 0 and 0.35
quantity = np.random.randint(1, 20, 8)               # Quantity as integers

# Creating the dataframe
df_multi = pd.DataFrame({'Sales': sales, 'Profit(%)': profit, 'Quantity': quantity}, index=index)

print(df_multi)

                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  187.50       0.23        18
                    two  109.33       0.29        15
Los Angeles Q1      one  137.55       0.28         4
                    two  324.69       0.17        13
Chicago     Q2      one  229.86       0.13        15
                    two  166.41       0.01        15
New York    Q2      one  327.16       0.03        13
                    two  166.01       0.08         9

In [2]:
df_multi.loc[('New York', 'Q1')]

C:\Users\Code Academy\AppData\Local\Temp\ipykernel_27756\3146562760.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  df_multi.loc[('New York', 'Q1')]

      Sales  Profit(%)  Quantity
ID
one  187.50       0.23        18
two  109.33       0.29        15

In [3]:
df_multi.loc[('New York', 'Q1', 'one')]

Sales        187.50
Profit(%)      0.23
Quantity      18.00
Name: (New York, Q1, one), dtype: float64

In [4]:
df_multi.loc[(slice(None), 'Q1'), :]

                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  187.50       0.23        18
                    two  109.33       0.29        15
Los Angeles Q1      one  137.55       0.28         4
                    two  324.69       0.17        13