In [32]:
import pandas as pd
import numpy as np

# Creating a more complex dataframe with multi-index
index = pd.MultiIndex.from_tuples([('New York', 'Q1', 'one'), ('New York', 'Q1', 'two'),
                                   ('Los Angeles', 'Q1', 'one'), ('Los Angeles', 'Q1', 'two'),
                                   ('Chicago', 'Q2', 'one'), ('Chicago', 'Q2', 'two'),
                                   ('New York', 'Q2', 'one'), ('New York', 'Q2', 'two')],
                                  names=['City', 'Quarter', 'ID'])

# Creating random data for Sales, Profit, and Quantity
sales = np.round(np.random.uniform(100, 500, 8), 2)  # Sales between 100 and 500
profit = np.round(np.random.uniform(0, 0.35, 8), 2)     # Profit between 0 and 0.35
quantity = np.random.randint(1, 20, 8)               # Quantity as integers

# Creating the dataframe
df_multi = pd.DataFrame({'Sales': sales, 'Profit(%)': profit, 'Quantity': quantity}, index=index)

print(df_multi)

                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  454.93       0.30        14
                    two  400.10       0.27         8
Los Angeles Q1      one  279.37       0.23         6
                    two  101.97       0.11         1
Chicago     Q2      one  134.56       0.11         8
                    two  460.60       0.28         1
New York    Q2      one  442.70       0.16        13
                    two  383.98       0.20        14

In [33]:
df_multi[df_multi['Sales']>200]

                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  454.93       0.30        14
                    two  400.10       0.27         8
Los Angeles Q1      one  279.37       0.23         6
Chicago     Q2      two  460.60       0.28         1
New York    Q2      one  442.70       0.16        13
                    two  383.98       0.20        14

In [34]:
df_multi.query('Sales>200')

                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  454.93       0.30        14
                    two  400.10       0.27         8
Los Angeles Q1      one  279.37       0.23         6
Chicago     Q2      two  460.60       0.28         1
New York    Q2      one  442.70       0.16        13
                    two  383.98       0.20        14

In [35]:
df_multi.query('Sales>200 and Quantity>5')

                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  454.93       0.30        14
                    two  400.10       0.27         8
Los Angeles Q1      one  279.37       0.23         6
New York    Q2      one  442.70       0.16        13
                    two  383.98       0.20        14

In [36]:
pd.qcut(df2["Salary"],
		q=2,
    labels=['Lower', 'higher'],
    precision=1, duplicates='drop')

NameError: name 'df2' is not defined

In [3]:
df_multi.loc[('New York', 'Q1')]

C:\Users\Code Academy\AppData\Local\Temp\ipykernel_18036\3146562760.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  df_multi.loc[('New York', 'Q1')]

      Sales  Profit(%)  Quantity
ID
one  244.88       0.23         1
two  125.95       0.05         8

In [4]:
df_multi.loc[('New York', 'Q1', 'one')]

Sales        244.88
Profit(%)      0.23
Quantity       1.00
Name: (New York, Q1, one), dtype: float64

In [12]:
df_multi.loc[(slice(None), slice(None), 'one')].reset_index()

          City Quarter   Sales  Profit(%)  Quantity
0     New York      Q1  244.88       0.23         1
1  Los Angeles      Q1  295.56       0.34         4
2      Chicago      Q2  137.15       0.10         1
3     New York      Q2  324.85       0.09        12

In [6]:
df_multi.loc['Chicago', 'Sales']

C:\Users\Code Academy\AppData\Local\Temp\ipykernel_18036\2142771342.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  df_multi.loc['Chicago', 'Sales']

Quarter  ID
Q2       one    137.15
         two    305.61
Name: Sales, dtype: float64

In [7]:
# ================================
# LEVEL 1
# ================================

# Q1: All data for New York
print("\nQ1")
print(df_multi.loc['New York'])

# Q2: New York in Q1
print("\nQ2")
print(df_multi.loc[('New York', 'Q1')])

# Q3: Los Angeles, Q1, ID two
print("\nQ3")
print(df_multi.loc[('Los Angeles', 'Q1', 'two')])

# Q4: Sales for Chicago
print("\nQ4")
print(df_multi.loc['Chicago', 'Sales'])

# Q5: Profit(%) for New York Q2
print("\nQ5")
print(df_multi.loc[('New York', 'Q2'), 'Profit(%)'])

Q1
              Sales  Profit(%)  Quantity
Quarter ID
Q1      one  244.88       0.23         1
        two  125.95       0.05         8
Q2      one  324.85       0.09        12
        two  456.48       0.20         3

Q2
      Sales  Profit(%)  Quantity
ID
one  244.88       0.23         1
two  125.95       0.05         8

Q3
Sales        116.67
Profit(%)      0.09
Quantity       6.00
Name: (Los Angeles, Q1, two), dtype: float64

Q4
Quarter  ID
Q2       one    137.15
         two    305.61
Name: Sales, dtype: float64

Q5
ID
one    0.09
two    0.20
Name: Profit(%), dtype: float64

C:\Users\Code Academy\AppData\Local\Temp\ipykernel_18036\4026906649.py:11: PerformanceWarning: indexing past lexsort depth may impact performance.
  print(df_multi.loc[('New York', 'Q1')])
C:\Users\Code Academy\AppData\Local\Temp\ipykernel_18036\4026906649.py:19: PerformanceWarning: indexing past lexsort depth may impact performance.
  print(df_multi.loc['Chicago', 'Sales'])
C:\Users\Code Academy\AppData\Local\Temp\ipykernel_18036\4026906649.py:23: PerformanceWarning: indexing past lexsort depth may impact performance.
  print(df_multi.loc[('New York', 'Q2'), 'Profit(%)'])

In [8]:
# ================================
# LEVEL 2
# ================================

# Q6: Sales & Quantity for New York Q1
print("\nQ6")
print(df_multi.loc[('New York', 'Q1'), ['Sales', 'Quantity']])

# Q7: Chicago Q2 → Sales only
print("\nQ7")
print(df_multi.loc[('Chicago', 'Q2'), 'Sales'])

# Q8: All rows where ID = 'one'
print("\nQ8")
print(df_multi.loc[(slice(None), slice(None), 'one'), :])

# Q9: All rows where Quarter = Q1
print("\nQ9")
print(df_multi.loc[(slice(None), 'Q1', slice(None)), :])

Q6
      Sales  Quantity
ID
one  244.88         1
two  125.95         8

Q7
ID
one    137.15
two    305.61
Name: Sales, dtype: float64

Q8
                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  244.88       0.23         1
Los Angeles Q1      one  295.56       0.34         4
Chicago     Q2      one  137.15       0.10         1
New York    Q2      one  324.85       0.09        12

Q9
                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  244.88       0.23         1
                    two  125.95       0.05         8
Los Angeles Q1      one  295.56       0.34         4
                    two  116.67       0.09         6

C:\Users\Code Academy\AppData\Local\Temp\ipykernel_18036\2111272754.py:7: PerformanceWarning: indexing past lexsort depth may impact performance.
  print(df_multi.loc[('New York', 'Q1'), ['Sales', 'Quantity']])
C:\Users\Code Academy\AppData\Local\Temp\ipykernel_18036\2111272754.py:11: PerformanceWarning: indexing past lexsort depth may impact performance.
  print(df_multi.loc[('Chicago', 'Q2'), 'Sales'])

In [9]:
# ================================
# LEVEL 4
# ================================

# Q14: New York → Quantity only
print("\nQ14")
print(df_multi.loc['New York', 'Quantity'])

# Q15: Quarter = Q2
print("\nQ15")
print(df_multi.loc[(slice(None), 'Q2', slice(None)), :])

# Q16: All cities, Q1, ID = one
print("\nQ16")
print(df_multi.loc[(slice(None), 'Q1', 'one'), :])

# Q17: Sales > 200
print("\nQ17")
print(df_multi[df_multi['Sales'] > 200])

# Q18: Quantity < 10 → only Quantity
print("\nQ18")
print(df_multi[df_multi['Quantity'] < 10][['Quantity']])

Q14
Quarter  ID
Q1       one     1
         two     8
Q2       one    12
         two     3
Name: Quantity, dtype: int32

Q15
                       Sales  Profit(%)  Quantity
City     Quarter ID
Chicago  Q2      one  137.15       0.10         1
                 two  305.61       0.17         9
New York Q2      one  324.85       0.09        12
                 two  456.48       0.20         3

Q16
                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  244.88       0.23         1
Los Angeles Q1      one  295.56       0.34         4

Q17
                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  244.88       0.23         1
Los Angeles Q1      one  295.56       0.34         4
Chicago     Q2      two  305.61       0.17         9
New York    Q2      one  324.85       0.09        12
                    two  456.48       0.20         3

Q18
                         Quantity
City        Quarter ID
New York    Q1      one         1
                    two         8
Los Angeles Q1      one         4
                    two         6
Chicago     Q2      one         1
                    two         9
New York    Q2      two         3

C:\Users\Code Academy\AppData\Local\Temp\ipykernel_18036\3102515786.py:7: PerformanceWarning: indexing past lexsort depth may impact performance.
  print(df_multi.loc['New York', 'Quantity'])

In [24]:
df_multi

                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  244.88       0.23         1
                    two  125.95       0.05         8
Los Angeles Q1      one  295.56       0.34         4
                    two  116.67       0.09         6
Chicago     Q2      one  137.15       0.10         1
                    two  305.61       0.17         9
New York    Q2      one  324.85       0.09        12
                    two  456.48       0.20         3

In [20]:
# Q19: Row with max Sales
df_multi["Sales"].idxmax()

('New York', 'Q2', 'two')

In [22]:
# Q20: Profit(%) > 0.2
df_multi[df_multi["Profit(%)"]>0.2]

                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  244.88       0.23         1
Los Angeles Q1      one  295.56       0.34         4

In [23]:
# Q21: Average Sales per City
cityG = df_multi.groupby("City")
cityG["Sales"].mean()

City
Chicago        221.380
Los Angeles    206.115
New York       288.040
Name: Sales, dtype: float64

In [ ]:
# Q22: Count per Quarter

In [10]:

# ================================
# LEVEL 5 (ADVANCED)
# ================================

# Q19: Row with max Sales
print("\nQ19")
print(df_multi.loc[df_multi['Sales'].idxmax()])

# Q20: Profit(%) > 0.2
print("\nQ20")
print(df_multi[df_multi['Profit(%)'] > 0.2])

# Q21: Average Sales per City
print("\nQ21")
print(df_multi.groupby('City')['Sales'].mean())

# Q22: Count per Quarter
print("\nQ22")
print(df_multi.groupby('Quarter').size())

Q19
Sales        456.48
Profit(%)      0.20
Quantity       3.00
Name: (New York, Q2, two), dtype: float64

Q20
                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  244.88       0.23         1
Los Angeles Q1      one  295.56       0.34         4

Q21
City
Chicago        221.380
Los Angeles    206.115
New York       288.040
Name: Sales, dtype: float64

Q22
Quarter
Q1    4
Q2    4
dtype: int64

In [13]:
df_multi.groupby('Quarter').count()

         Sales  Profit(%)  Quantity
Quarter
Q1           4          4         4
Q2           4          4         4

In [14]:
df_multi.groupby('Quarter').nunique()

         Sales  Profit(%)  Quantity
Quarter
Q1           4          4         4
Q2           4          4         4

In [25]:
df_multi.index.get_level_values("Quarter").value_counts()
df_multi.groupby(['Quarter']).size()
df_multi.groupby(['Quarter']).count()
df_multi.groupby(['Quarter']).shape

Quarter
Q1    4
Q2    4
Name: count, dtype: int64

In [29]:
df_multi.index.get_level_values("Quarter")

Index(['Q1', 'Q1', 'Q1', 'Q1', 'Q2', 'Q2', 'Q2', 'Q2'], dtype='object', name='Quarter')

In [31]:
df_multi.MultiIndex.get_level_values("Quarter")

AttributeError: 'DataFrame' object has no attribute 'MultiIndex'

In [27]:
df_multi.groupby(['Quarter']).count()

         Sales  Profit(%)  Quantity
Quarter
Q1           4          4         4
Q2           4          4         4

In [28]:
df_multi.groupby(['Quarter']).size()

Quarter
Q1    4
Q2    4
dtype: int64